### PR TITLE
Fix potential shading issue & version meta

### PR DESCRIPTION
**Pull request by vectrixdevelops**
🛥

### CODE REVIEW

**Comment by me4502** [comment]
Wait so what's the issue and how does this solve it

**Comment by vectrixdevelops** [comment]
If either an AntiCheat or Plugin Hook shades in Guava (for whatever reason), this public facing method is highly likely to cause a conflict with the classpath (which I happen to experience when testing a hook and Guardian). Simple fix of changing the public facing type to just a java lang List with the Guava collection implemented underneath fixes the issue. As a service I think it's quite important to fix an issue like this as it is unknown to how it is implemented.

**Comment by vectrixdevelops** [comment]
Adding the version to the plugin annotation also allows me to get the correct version of the plugin from the SpongeAPI. (Or else it relies on the jar name, which isn't the most reliable)

**Comment by me4502** [comment]
Perfect, thanks.

**Pull request merged**
